/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupNameRouteImport } from './routes/signup.name'
import { Route as SignupAgeRouteImport } from './routes/signup.age'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupNameRoute = SignupNameRouteImport.update({
  id: '/signup/name',
  path: '/signup/name',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupAgeRoute = SignupAgeRouteImport.update({
  id: '/signup/age',
  path: '/signup/age',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup/age': typeof SignupAgeRoute
  '/signup/name': typeof SignupNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup/age': typeof SignupAgeRoute
  '/signup/name': typeof SignupNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signup/age': typeof SignupAgeRoute
  '/signup/name': typeof SignupNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signup/age' | '/signup/name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signup/age' | '/signup/name'
  id: '__root__' | '/' | '/signup/age' | '/signup/name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignupAgeRoute: typeof SignupAgeRoute
  SignupNameRoute: typeof SignupNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/name': {
      id: '/signup/name'
      path: '/signup/name'
      fullPath: '/signup/name'
      preLoaderRoute: typeof SignupNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/age': {
      id: '/signup/age'
      path: '/signup/age'
      fullPath: '/signup/age'
      preLoaderRoute: typeof SignupAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignupAgeRoute: SignupAgeRoute,
  SignupNameRoute: SignupNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
