/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupNameRouteImport } from './routes/signup.name'
import { Route as SignupGenderRouteImport } from './routes/signup.gender'
import { Route as SignupDoneRouteImport } from './routes/signup.done'
import { Route as SignupBioRouteImport } from './routes/signup.bio'
import { Route as SignupAgeRouteImport } from './routes/signup.age'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupNameRoute = SignupNameRouteImport.update({
  id: '/signup/name',
  path: '/signup/name',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupGenderRoute = SignupGenderRouteImport.update({
  id: '/signup/gender',
  path: '/signup/gender',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupDoneRoute = SignupDoneRouteImport.update({
  id: '/signup/done',
  path: '/signup/done',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupBioRoute = SignupBioRouteImport.update({
  id: '/signup/bio',
  path: '/signup/bio',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupAgeRoute = SignupAgeRouteImport.update({
  id: '/signup/age',
  path: '/signup/age',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup/age': typeof SignupAgeRoute
  '/signup/bio': typeof SignupBioRoute
  '/signup/done': typeof SignupDoneRoute
  '/signup/gender': typeof SignupGenderRoute
  '/signup/name': typeof SignupNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup/age': typeof SignupAgeRoute
  '/signup/bio': typeof SignupBioRoute
  '/signup/done': typeof SignupDoneRoute
  '/signup/gender': typeof SignupGenderRoute
  '/signup/name': typeof SignupNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup/age': typeof SignupAgeRoute
  '/signup/bio': typeof SignupBioRoute
  '/signup/done': typeof SignupDoneRoute
  '/signup/gender': typeof SignupGenderRoute
  '/signup/name': typeof SignupNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup/age'
    | '/signup/bio'
    | '/signup/done'
    | '/signup/gender'
    | '/signup/name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup/age'
    | '/signup/bio'
    | '/signup/done'
    | '/signup/gender'
    | '/signup/name'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup/age'
    | '/signup/bio'
    | '/signup/done'
    | '/signup/gender'
    | '/signup/name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupAgeRoute: typeof SignupAgeRoute
  SignupBioRoute: typeof SignupBioRoute
  SignupDoneRoute: typeof SignupDoneRoute
  SignupGenderRoute: typeof SignupGenderRoute
  SignupNameRoute: typeof SignupNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/name': {
      id: '/signup/name'
      path: '/signup/name'
      fullPath: '/signup/name'
      preLoaderRoute: typeof SignupNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/gender': {
      id: '/signup/gender'
      path: '/signup/gender'
      fullPath: '/signup/gender'
      preLoaderRoute: typeof SignupGenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/done': {
      id: '/signup/done'
      path: '/signup/done'
      fullPath: '/signup/done'
      preLoaderRoute: typeof SignupDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/bio': {
      id: '/signup/bio'
      path: '/signup/bio'
      fullPath: '/signup/bio'
      preLoaderRoute: typeof SignupBioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/age': {
      id: '/signup/age'
      path: '/signup/age'
      fullPath: '/signup/age'
      preLoaderRoute: typeof SignupAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupAgeRoute: SignupAgeRoute,
  SignupBioRoute: SignupBioRoute,
  SignupDoneRoute: SignupDoneRoute,
  SignupGenderRoute: SignupGenderRoute,
  SignupNameRoute: SignupNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
